site_name: WIZNET

nav:
  - Home: index.md
  - Blog:
      - Blog: blog/index.md

theme:
  name: material
  logo: assets/images/wzntxyzlogo.png
  favicon: "favicon.ico"
  palette:
    primary: black  # Replacing purple
    accent: blue  # Or any color you prefer
  font:
    text: "Inter"
    code: "JetBrains Mono"

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - blog:
      enabled: true
      blog_dir: blog
      archive: true
      categories: true
  - tags
