site_name: WIZNET

nav:
  - Home: index.md
  - Blog: blog/index.md

theme:
  name: material
  logo: assets/images/wzntxyzlogo.png
  favicon: "favicon.ico"
  palette:
    scheme: slate  # Forces dark mode
    primary: black
    accent: blue

  font:
    text: "Inter"
    code: "JetBrains Mono"

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - blog:
      enabled: true
      blog_dir: blog
      archive: true
      categories: true
  - tags
