name: Fetch Notion Posts & Publish to Blog

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install requests markdownify notion-client

      - name: Debug Available Secrets
        run: |
          echo "Available Secrets:"
          echo "${{ toJson(secrets) }}"

      - name: Fetch Notion Data & Commit to GitHub
        run: python fetch_notion_posts.py '${{ secrets.NOTION_DATABASE_ID }}' '${{ secrets.NOTION_TOKEN }}' '${{ secrets.GH_PAT_WIZNET }}'
